// File: src/components/settings/settingsStyles.ts
// Shared styles of the SettingsModal sections.
import { StyleSheet } from 'react-native';

export const settingsStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  container: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    width: '100%',
    maxWidth: 320,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  title: {
    fontSize: 17,
    fontWeight: '600',
    color: '#1f2937',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  section: {
    padding: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  scaleOptions: {
    flexDirection: 'row',
    gap: 8,
  },
  scaleOption: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  scaleOptionActive: {
    backgroundColor: '#e0f2fe',
    borderColor: '#0ea5e9',
  },
  scaleIconContainer: {
    marginBottom: 6,
  },
  scaleLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 2,
  },
  scaleLabelActive: {
    color: '#0ea5e9',
  },
  scaleDescription: {
    fontSize: 10,
    color: '#9ca3af',
  },
  scrollContent: {
    maxHeight: 500,
  },
  importResultText: {
    fontSize: 11,
    color: '#374151',
    backgroundColor: '#f0fdf4',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  connectionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f9fafb',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  connectionInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  connectionIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  connectionDetails: {
    flex: 1,
  },
  connectionName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 2,
  },
  connectedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  connectedText: {
    fontSize: 11,
    color: '#22c55e',
    fontWeight: '500',
  },
  disconnectedText: {
    fontSize: 11,
    color: '#9ca3af',
  },
  connectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#e0f2fe',
    borderRadius: 6,
  },
  connectButtonText: {
    fontSize: 11,
    fontWeight: '600',
  },
  disconnectButton: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#fef2f2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  versionSection: {
    padding: 16,
    alignItems: 'center',
  },
  versionText: {
    fontSize: 11,
    color: '#9ca3af',
  },
  statusBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#f0f9ff',
    padding: 8,
    borderRadius: 6,
    marginBottom: 12,
  },
  statusText: {
    fontSize: 12,
    color: '#0066b3',
    fontWeight: '500',
  },
  inputGroup: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#6b7280',
    marginBottom: 4,
  },
  input: {
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    color: '#1f2937',
  },
  pinInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pinInput: {
    flex: 1,
  },
  pinToggle: {
    position: 'absolute',
    right: 10,
    padding: 4,
  },
  formButtons: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  cancelButton: {
    flex: 1,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
  },
  cancelButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6b7280',
  },
  submitButton: {
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#0066b3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ffffff',
  },
  tanMethodList: {
    gap: 8,
  },
  tanMethodOption: {
    padding: 12,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  tanMethodName: {
    fontSize: 13,
    fontWeight: '500',
    color: '#1f2937',
    textAlign: 'center',
  },
  doneSection: {
    alignItems: 'center',
    gap: 8,
  },
  doneText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#22c55e',
  },
  accountInfo: {
    fontSize: 12,
    color: '#6b7280',
    fontFamily: 'monospace',
  },
  // PayPal styles
  paypalButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  backupButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  backupButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  syncCard: {
    backgroundColor: '#f9fafb',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  syncStatusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    backgroundColor: '#ffffff',
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  syncButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#e8f4fd',
    borderRadius: 6,
  },
  clearCacheButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#fef2f2',
    borderRadius: 6,
  },
  clearCacheText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#ef4444',
  },
  csvResultBox: {
    backgroundColor: '#f0fdf4',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  csvResultText: {
    fontSize: 11,
    color: '#166534',
    lineHeight: 16,
  },
  // Warning modal styles
  warningOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  warningContainer: {
    backgroundColor: '#dc2626',
    borderRadius: 16,
    width: '100%',
    maxWidth: 400,
    borderWidth: 4,
    borderColor: '#fef2f2',
    shadowColor: '#dc2626',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    elevation: 20,
  },
  warningHeader: {
    backgroundColor: '#991b1b',
    padding: 20,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    alignItems: 'center',
  },
  warningTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: 2,
  },
  warningContent: {
    padding: 24,
  },
  warningText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 12,
  },
  warningSubtext: {
    fontSize: 14,
    color: '#fecaca',
    textAlign: 'center',
    marginBottom: 24,
  },
  warningButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  warningCancelButton: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#e5e7eb',
  },
  warningCancelText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1f2937',
  },
  warningConfirmButton: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    backgroundColor: '#991b1b',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#7f1d1d',
  },
  warningConfirmText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ffffff',
  },
  warningDangerButton: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    backgroundColor: '#7f1d1d',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#450a0a',
  },
  warningDangerText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: 1,
  },
  // Balance styles
  balanceInputContainer: {
    backgroundColor: '#f9fafb',
    borderRadius: 10,
    padding: 12,
  },
  balanceInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  balanceInputLabel: {
    width: 80,
    fontSize: 13,
    color: '#374151',
    fontWeight: '500',
  },
  balanceInput: {
    flex: 1,
    height: 36,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 6,
    paddingHorizontal: 8,
    fontSize: 14,
    color: '#1f2937',
    textAlign: 'right',
  },
  currencyLabel: {
    marginLeft: 8,
    fontSize: 14,
    color: '#6b7280',
    width: 12,
  },
  saveBalanceButton: {
    marginLeft: 12,
    padding: 4,
  },
  balanceHelpText: {
    fontSize: 11,
    color: '#9ca3af',
    marginTop: 4,
    fontStyle: 'italic',
  },
  // AI Key styles
  aiKeyContainer: {
    backgroundColor: '#f9fafb',
    borderRadius: 10,
    padding: 12,
  },
  keyInputRow: {
    flexDirection: 'row',
    gap: 8,
  },
  keyInput: {
    flex: 1,
    height: 40,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 13,
    color: '#1f2937',
  },
  saveKeyButton: {
    backgroundColor: '#0ea5e9',
    paddingHorizontal: 16,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveKeyButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  keyStatusBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    borderRadius: 8,
    padding: 10,
  },
  keyStatusInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  keyStatusText: {
    fontSize: 13,
    color: '#166534',
    fontWeight: '500',
  },
  deleteKeyButton: {
    padding: 4,
  },
});
